name = "wlvpn"
main = "_worker.js"
compatibility_date = "2024-12-18"

# KV для хранения подписок
[[kv_namespaces]]
binding = "KV"
id = "b795add16af1425f980fe319d2907b67"

# Логи
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true