name = "wlvpn"
main = "_worker.js"
compatibility_date = "2024-12-18"

# =========================
# KV
# =========================

[[kv_namespaces]]
binding = "KV"
id = "b795add16af1425f980fe319d2907b67"


# =========================
# D1 DATABASE
# =========================

[[d1_databases]]
binding = "DB"
database_name = "wlvpn-db"
database_id = "c2374e81-be12-4356-a054-ec572de7a5fd"


# =========================
# CRON
# =========================

[triggers]
crons = [
  "*/30 * * * *",
  "0 0 * * *"
]


# =========================
# LOGS
# =========================

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true


[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true